server:
  port: 9111
token:
  # token 令牌的 header 标识
  header: Authorization
  # token 有效时间(分钟),默认30分钟
  expire: 30
spring:
  profiles:
    active: mysql,redis
  application:
    name: north-admin
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    cache-enabled: true
logging:
  level:
    root: info
    com:
      luoke:
        iceblog:
          admin:
            mapper: debug
